<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Overview" data-toc-modified-id="Overview-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Overview</a></span></li><li><span><a href="#Notebook-Configuration" data-toc-modified-id="Notebook-Configuration-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Notebook Configuration</a></span><ul class="toc-item"><li><span><a href="#Google-drive" data-toc-modified-id="Google-drive-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Google drive</a></span></li><li><span><a href="#Warning" data-toc-modified-id="Warning-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Warning</a></span></li><li><span><a href="#Matplotlib" data-toc-modified-id="Matplotlib-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Matplotlib</a></span></li><li><span><a href="#TensorFlow" data-toc-modified-id="TensorFlow-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>TensorFlow</a></span></li><li><span><a href="#Random-seed" data-toc-modified-id="Random-seed-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span>Random seed</a></span></li></ul></li><li><span><a href="#Data-Preprocessing" data-toc-modified-id="Data-Preprocessing-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Data Preprocessing</a></span></li><li><span><a href="#Hyperparameter-Tuning" data-toc-modified-id="Hyperparameter-Tuning-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Hyperparameter Tuning</a></span></li><li><span><a href="#Model-Selection" data-toc-modified-id="Model-Selection-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Model Selection</a></span></li><li><span><a href="#Generating-the-Submission-File" data-toc-modified-id="Generating-the-Submission-File-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Generating the Submission File</a></span><ul class="toc-item"><li><span><a href="#Creating-the-directory-for-the-submission-file" data-toc-modified-id="Creating-the-directory-for-the-submission-file-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Creating the directory for the submission file</a></span></li><li><span><a href="#Generating-the-submission-file" data-toc-modified-id="Generating-the-submission-file-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Generating the submission file</a></span></li></ul></li></ul></div>

<b>
<p>
<center>
<font size="5">
Popular Machine Learning Methods: Idea, Practice and Math
</font>
</center>
</p>

<p>
<center>
<font size="4">
Part 2, Chapter 2, Section 2: Training Shallow Models
</font>
</center>
</p>
    
<p>
<center>
<font size="4">
Homework 1
</font>
</center>
</p>

<p>
<center>
<font size="3">
Data Science, Columbian College of Arts & Sciences, George Washington University
</font>
</center>
</p>

<p>
<center>
<font size="3">
Yuxiao Huang
</font>
</center>
</p>
</b>

# Overview

- This notebook includes homework 1 for Training Shallow Models (Part 2, Chapter 2, Section 2).
- See the accompanied slides in our [github repository](https://github.com/yuxiaohuang/teaching/tree/master/gwu/machine_learning_I/fall_2025/slides/p2_shallow_learning/p2_c2_supervised_learning/p2_c2_s2_training_shallow_models).
- Here we will work on kaggle competation [New York City Taxi Trip Duration](https://www.kaggle.com/c/nyc-taxi-trip-duration/overview).
- The goal of this homework is tweaking the pipeline (including data preprocessing, hyperparameter tuning and model selection) implemented in [/p2 c2 s2 training shallow models/case_study](https://github.com/yuxiaohuang/teaching/blob/main/gwu/machine_learning_I/fall_2025/code/p2_shallow_learning/p2_c2_supervised_learning/p2_c2_s2_training_shallow_models/case_study/case_study.ipynb) to make it work for the new kaggle competation mentioned above.
- Complete the missing parts indicated by # Implement me.
- Particularly, the code should
    - be bug-free (note that the output produced by your solution may not necessarily be the same as the provided output, due to version issues)
    - be commented
- **The baseline for this assignment is -0.332515. As per the grading rubrics (section 15 of the syllabus), if the validation score of your best model is lower than or the same as the baseline, you will only receive 80% of the full mark. See more details in the grading rubrics.**
- Submit an ipynb file named homework_1.ipynb to [blackboard](https://blackboard.gwu.edu) folder /Assignments/Homework_1/.

# Notebook Configuration

## Google drive

In [1]:
from google.colab import drive
import sys

# Mount Google Drive
drive.mount('/content/drive')

# Get the absolute path of the current folder
abspath_curr = '/content/drive/My Drive/Colab Notebooks/teaching/gwu/machine_learning_I/code/p2_shallow_learning/p2_c2_supervised_learning/p2_c2_s2_training_shallow_models/homework_1/'

# Get the absolute path of the shallow utilities folder
abspath_util_shallow = '/content/drive/My Drive/Colab Notebooks/teaching/gwu/machine_learning_I/spring_2026/code/utilities/p2_shallow_learning/'

# Get the absolute path of the shallow models folder
abspath_model_shallow = '/content/drive/My Drive/Colab Notebooks/teaching/gwu/machine_learning_I/spring_2026/code/models/p2_shallow_learning/'

Mounted at /content/drive

## Warning

In [2]:
import warnings

# Ignore warnings
warnings.filterwarnings('ignore')

## Matplotlib

In [3]:
import matplotlib.pyplot as plt
%matplotlib inline

# Set matplotlib sizes
plt.rc('font', size=20)
plt.rc('axes', titlesize=20)
plt.rc('axes', labelsize=20)
plt.rc('xtick', labelsize=20)
plt.rc('ytick', labelsize=20)
plt.rc('legend', fontsize=20)
plt.rc('figure', titlesize=20)

## TensorFlow

In [4]:
# The magic below allows us to use tensorflow version 2.x
%tensorflow_version 2.x
import tensorflow as tf
from tensorflow import keras

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.

## Random seed

In [5]:
# The random seed
random_seed = 42

# Set random seed in tensorflow
tf.random.set_seed(random_seed)

# Set random seed in numpy
import numpy as np
np.random.seed(random_seed)

# Data Preprocessing
**Note: You will need to specify the date time variables, *datetime_vars*, when handling date time variables**.

In [6]:
# Change working directory to the absolute path of the shallow utilities folder
%cd $abspath_util_shallow

# Import the shallow utitilities
%run pmlm_utilities_shallow.ipynb

/content/drive/My Drive/Colab Notebooks/teaching/gwu/machine_learning_I/spring_2026/code/utilities/p2_shallow_learning

In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# load train and test data
df_raw_train = pd.read_csv(abspath_curr + 'data/train.csv', header=0)
df_train = df_raw_train.copy(deep=True)

df_raw_test = pd.read_csv(abspath_curr + 'data/test.csv', header=0)
df_test = df_raw_test.copy(deep=True)

target = 'trip_duration'

print("df_train:", df_train.shape)
print("df_test:", df_test.shape)
display(df_train.head())

# split train into train(80%) and val(20%)
df_train, df_val = train_test_split(df_train, train_size=0.8, random_state=random_seed)
df_train, df_val = df_train.reset_index(drop=True), df_val.reset_index(drop=True)

# check common variables
df_common_var = common_var_checker(df_train, df_val, df_test, target)

uncommon_feature_train_not_val_test = np.setdiff1d(df_train.columns, df_common_var['common var'])
uncommon_feature_val_not_train_test = np.setdiff1d(df_val.columns, df_common_var['common var'])
uncommon_feature_test_not_train_val = np.setdiff1d(df_test.columns, df_common_var['common var'])

print("Uncommon in train:", uncommon_feature_train_not_val_test)

# drop uncommon features
df_train = df_train.drop(columns=uncommon_feature_train_not_val_test)
df_val = df_val.drop(columns=uncommon_feature_val_not_train_test)
df_test = df_test.drop(columns=uncommon_feature_test_not_train_val)

# find and remove identifiers
df = pd.concat([df_train, df_val, df_test], sort=False)
df_id = id_checker(df)
print("Identifiers:", list(df_id.columns))

df_train.drop(columns=np.intersect1d(df_id.columns, df_train.columns), inplace=True)
df_val.drop(columns=np.intersect1d(df_id.columns, df_val.columns), inplace=True)
df_test.drop(columns=np.intersect1d(df_id.columns, df_test.columns), inplace=True)

# handle datetime
datetime_vars = ['pickup_datetime']

df_train = datetime_transformer(df_train, datetime_vars)
df_val = datetime_transformer(df_val, datetime_vars)
df_test = datetime_transformer(df_test, datetime_vars)

# feature engineering
def add_features(df):
    d = df.copy(deep=True)

    # calculate haversine distance between pickup and dropoff
    R = 6371
    lat1 = np.radians(d['pickup_latitude'])
    lat2 = np.radians(d['dropoff_latitude'])
    dlat = np.radians(d['dropoff_latitude'] - d['pickup_latitude'])
    dlon = np.radians(d['dropoff_longitude'] - d['pickup_longitude'])
    a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    d['haversine_distance'] = 2 * R * np.arcsin(np.sqrt(a))

    # coordinate differences
    d['abs_diff_longitude'] = np.abs(d['dropoff_longitude'] - d['pickup_longitude'])
    d['abs_diff_latitude'] = np.abs(d['dropoff_latitude'] - d['pickup_latitude'])

    # day of week
    d['pickup_datetime_dayofweek'] = pd.to_datetime(
        d[['pickup_datetime_year', 'pickup_datetime_month', 'pickup_datetime_day']].rename(
            columns={'pickup_datetime_year': 'year', 'pickup_datetime_month': 'month', 'pickup_datetime_day': 'day'}
        )
    ).dt.dayofweek

    # these are not continuous so convert to categorical
    d['pickup_datetime_hour'] = d['pickup_datetime_hour'].astype(str)
    d['pickup_datetime_month'] = d['pickup_datetime_month'].astype(str)
    d['pickup_datetime_dayofweek'] = d['pickup_datetime_dayofweek'].astype(str)
    d['vendor_id'] = d['vendor_id'].astype(str)

    # drop useless columns (year is all 2016, minute/second are noise)
    d = d.drop(columns=['pickup_datetime_year', 'pickup_datetime_day',
                         'pickup_datetime_minute', 'pickup_datetime_second'])

    return d

df_train = add_features(df_train)
df_val = add_features(df_val)
df_test = add_features(df_test)

print("Columns:", list(df_train.columns))

# check missing values
df = pd.concat([df_train, df_val, df_test], sort=False)
df_nan = nan_checker(df)
print("Missing values:")
display(df_nan)

df_miss = df_nan[df_nan['dtype'] == 'float64'].reset_index(drop=True)

df_train = df.iloc[:df_train.shape[0], :]
df_val = df.iloc[df_train.shape[0]:df_train.shape[0] + df_val.shape[0], :]
df_test = df.iloc[df_train.shape[0] + df_val.shape[0]:, :]

# impute with mean
if len(df_miss['var']) > 0:
    si = SimpleImputer(missing_values=np.nan, strategy='mean')
    df_train[df_miss['var']] = si.fit_transform(df_train[df_miss['var']])
    df_val[df_miss['var']] = si.transform(df_val[df_miss['var']])
    df_test[df_miss['var']] = si.transform(df_test[df_miss['var']])

# encoding
df = pd.concat([df_train, df_val, df_test], sort=False)
df_cat = cat_var_checker(df)
print("Categorical variables:")
display(df_cat)

# one-hot encode
if len(df_cat) > 0:
    df = pd.get_dummies(df, columns=np.setdiff1d(df_cat['var'], [target]))

df_train = df.iloc[:df_train.shape[0], :]
df_val = df.iloc[df_train.shape[0]:df_train.shape[0] + df_val.shape[0], :]
df_test = df.iloc[df_train.shape[0] + df_val.shape[0]:, :]

print("df_train shape after encoding:", df_train.shape)

# split feature and target
X_train = df_train[np.setdiff1d(df_train.columns, [target])].values
X_val = df_val[np.setdiff1d(df_val.columns, [target])].values
X_test = df_test[np.setdiff1d(df_test.columns, [target])].values

y_train = df_train[target].values
y_val = df_val[target].values
y_test = df_test[target].values

# standardize
ss = StandardScaler()

X_train = ss.fit_transform(X_train)
X_val = ss.transform(X_val)
X_test = ss.transform(X_test)

y_train = ss.fit_transform(y_train.reshape(-1, 1)).reshape(-1)
y_val = ss.transform(y_val.reshape(-1, 1)).reshape(-1)
y_test = ss.transform(y_test.reshape(-1, 1)).reshape(-1)

df_train: (1458644, 11)
df_test: (625134, 9)

,id,vendor_id,pickup_datetime,dropoff_datetime,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,store_and_fwd_flag,trip_duration
0,id2875421,2,2016-03-14 17:24:55,2016-03-14 17:32:30,1,-73.982155,40.767937,-73.964630,40.765602,N,455
1,id2377394,1,2016-06-12 00:43:35,2016-06-12 00:54:38,1,-73.980415,40.738564,-73.999481,40.731152,N,663
2,id3858529,2,2016-01-19 11:35:24,2016-01-19 12:10:48,1,-73.979027,40.763939,-74.005333,40.710087,N,2124
3,id3504673,2,2016-04-06 19:32:31,2016-04-06 19:39:40,1,-74.010040,40.719971,-74.012268,40.706718,N,429
4,id2181028,2,2016-03-26 13:30:55,2016-03-26 13:38:10,1,-73.973053,40.793209,-73.972923,40.782520,N,435

Uncommon in train: ['dropoff_datetime']
Identifiers: ['id']
Columns: ['vendor_id', 'passenger_count', 'pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude', 'store_and_fwd_flag', 'trip_duration', 'pickup_datetime_month', 'pickup_datetime_hour', 'haversine_distance', 'abs_diff_longitude', 'abs_diff_latitude', 'pickup_datetime_dayofweek']
Missing values:

             var  proportion    dtype
0  trip_duration         0.3  float64

Categorical variables:

                         var  nunique
0       pickup_datetime_hour       24
1  pickup_datetime_dayofweek        7
2      pickup_datetime_month        6
3                  vendor_id        2
4         store_and_fwd_flag        2

df_train shape after encoding: (1166915, 50)

# Hyperparameter Tuning

In [8]:
from sklearn.linear_model import SGDRegressor, Ridge, Lasso
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

# added ridge and lasso to compare different regularization
models = {
    'sgd': SGDRegressor(random_state=random_seed),
    'ridge': Ridge(),
    'lasso': Lasso(random_state=random_seed)
}

pipes = {}
for acronym, model in models.items():
    pipes[acronym] = Pipeline([('model', model)])

X_train_val, y_train_val, ps = get_train_val_ps(X_train, y_train, X_val, y_val)

# parameter grids
param_grids = {}

param_grids['sgd'] = [{'model__eta0': [0.0001, 0.001, 0.01],
                        'model__alpha': [0.0001, 0.001, 0.01, 0.1]}]

param_grids['ridge'] = [{'model__alpha': [0.01, 0.1, 1.0, 10.0]}]

param_grids['lasso'] = [{'model__alpha': [0.0001, 0.001, 0.01, 0.1]}]

# make directory
directory = os.path.dirname(abspath_curr + 'result/cv_results/GridSearchCV/')
if not os.path.exists(directory):
    os.makedirs(directory)

# run grid search for each model
best_score_params_estimator_gs = []

for acronym in pipes.keys():
    print(f"Training {acronym}...")

    gs = GridSearchCV(estimator=pipes[acronym],
                      param_grid=param_grids[acronym],
                      scoring='neg_mean_squared_error',
                      n_jobs=2,
                      cv=ps,
                      return_train_score=True)

    gs = gs.fit(X_train_val, y_train_val)

    best_score_params_estimator_gs.append([gs.best_score_, gs.best_params_, gs.best_estimator_])

    cv_results = pd.DataFrame.from_dict(gs.cv_results_).sort_values(by=['rank_test_score', 'std_test_score'])

    important_columns = ['rank_test_score',
                         'mean_test_score',
                         'std_test_score',
                         'mean_train_score',
                         'std_train_score',
                         'mean_fit_time',
                         'std_fit_time',
                         'mean_score_time',
                         'std_score_time']

    cv_results = cv_results[important_columns + sorted(list(set(cv_results.columns) - set(important_columns)))]
    cv_results.to_csv(path_or_buf=abspath_curr + 'result/cv_results/GridSearchCV/' + acronym + '.csv', index=False)

best_score_params_estimator_gs = sorted(best_score_params_estimator_gs, key=lambda x: x[0], reverse=True)

pd.DataFrame(best_score_params_estimator_gs, columns=['best_score', 'best_param', 'best_estimator'])

Training sgd...
Training ridge...
Training lasso...

,best_score,best_param,best_estimator
0,-0.325847,{'model__alpha': 0.01},(Ridge(alpha=0.01))
1,-0.325854,{'model__alpha': 0.0001},"(Lasso(alpha=0.0001, random_state=42))"
2,-0.325919,"{'model__alpha': 0.1, 'model__eta0': 0.001}","(SGDRegressor(alpha=0.1, eta0=0.001, random_st..."

# Model Selection

In [9]:
# Get the best_score, best_params and best_estimator obtained by GridSearchCV
best_score_gs, best_params_gs, best_estimator_gs = best_score_params_estimator_gs[0]

print(f"Best validation score (neg MSE): {best_score_gs}")
print(f"Best parameters: {best_params_gs}")
print(f"Best estimator: {best_estimator_gs}")

Best validation score (neg MSE): -0.3258474986997439
Best parameters: {'model__alpha': 0.01}
Best estimator: Pipeline(steps=[('model', Ridge(alpha=0.01))])

# Generating the Submission File
Use the best model selected earlier to generate the submission file for this kaggle competition.

## Creating the directory for the submission file

In [10]:
# Make directory
directory = os.path.dirname(abspath_curr + 'result/submission/')
if not os.path.exists(directory):
    os.makedirs(directory)

## Generating the submission file

In [11]:
# Get the prediction on the testing data using best_model
y_test_pred = best_estimator_gs.predict(X_test)

# Get the dataframe of y_test_pred, which has the same shape as df_train
df_y_test_pred = pd.DataFrame(np.tile(y_test_pred.reshape(-1, 1), df_train.shape[1]),
                              columns=df_train.columns)

# Transform df_y_test_pred back to the original scale
df_y_test_pred = pd.DataFrame(ss.inverse_transform(df_y_test_pred),
                              columns=df_train.columns)

# Get the submission dataframe
df_submit = pd.DataFrame(np.hstack((df_raw_test[['id']], df_y_test_pred[[target]])),
                         columns=['id', target])

# Generate the submission file
df_submit.to_csv(abspath_curr + 'result/submission/submission.csv', index=False)